### ISSUE TITLE
Show title at narrowest setting

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#176]
On the narrowest window setting, and mobile, can we display the Plural Research Experiment title and "_An experiment in collective intelligence and innovation_" subtitle? The small font version that we had before? At wider settings keep the large version we have now

**Comment by thewanderingeditor** [comment]
I agree this isn't ideal. At what width does the text currently disapper?

**Comment by camilovegag** [comment]
## Header breakpoints

### From [0px to 639px]:
![mobile](https://github.com/lexicongovernance/forum-frontend/assets/59750365/2b8c1e59-7527-454a-a0bf-cfb9cebe1469)

### From [640px to 1079px]:
![laptop](https://github.com/lexicongovernance/forum-frontend/assets/59750365/f189e1ea-044d-49ab-9287-3b849d989933)

### From [1080px to n px]:
It will have a max width of 1080px and the rest will be horizontal spacing
![desktop](https://github.com/lexicongovernance/forum-frontend/assets/59750365/9a2e4e86-355c-4cbd-82ea-eef53132bf9c)

**Comment by camilovegag** [comment]
Not looking as good as it should, will go with option `ii`

https://github.com/lexicongovernance/forum-frontend/assets/59750365/d29f9c73-9eff-4302-9b20-40c6417ca368

**Comment by thewanderingeditor** [comment]
Oh sorry, I didn't mean that as two options: I think we should do both

**Comment by camilovegag** [comment]
Oh ok, gotcha, what do you think about this:

https://github.com/lexicongovernance/forum-frontend/assets/59750365/66c6067c-fb7d-40e3-b140-8a2b21cae314

Subtitle will disappear at 630px, and Title will disapear at 413px, as 414px its the width for some bigger iPhones :)

**Comment by lexicon-admin** [comment]
I think ideally the title would display on most phones.

In  your example earlier with the reduced logo size, would that affect every width? i.e., could we drop the logo size only below 414px?

**Comment by camilovegag** [comment]
Looks alright at 320px, full support stops around 336px, but I think this works for us:

https://github.com/lexicongovernance/forum-frontend/assets/59750365/c535abde-8106-402b-86cf-1373e51f0eed

**Comment by thewanderingeditor** [comment]
Regretfully reopening this one 😭

Got a request to show the subtitle as well as the title on mobile... I would again not try to get this working at the absolute narrowest, but instead focus on the most likely mobile widths
