### ISSUE TITLE
Update Berlin results page

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#242]
Some requested adjustments for how (and which) results are displayed in the results page for Berlin:

- Move global results panel to the bottom, beneath text "Overall Statistics"
- Remove "Leaderboard" wording
- Add possibility for extra / replacement text at the top by Results. The requested example is "Research the Community Loves", but the default should remain as "Results for [Question title]"

For each option:

- Hearts: [Number of hearts allocated]
- Voters: [Number of distinct voters]
- Groups: [Number of distinct groups]

For groups, add a dropdown which lists all the distinct groups (alphabetical order for now, maybe a different order in future)

Beneath all this, show the full description related to the option (if it exists)

**Comment by camilovegag** [comment]
Add description to expandable cards and expandable distinct groups inside the card as well.
