### ISSUE TITLE
Changes for demo on 21/02

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#246]
A summary of changes needed for the demo on 21st February. Some / all of these are covered by existing issues and PRs. Just wanted to collect everything in one place.

Landing page - no change

Onboarding/Registration - no changes

Agenda page / link:
- [x] Agenda link takes user to open agenda
- [x] Agenda page shows proposals divided by Open / Upcoming / Closed status
- [x] Open votes show "Closes on [Ending Date]"
- [x] Upcoming votes show "Opens on [Starting Date]"
- [x] Closed votes show "Closed on [Ending Date]"
- [x] Clicking a closed vote takes you directly to the results page for that vote

Vote page:
- [x] Remove "Show results" link (#240)
- [x] Replace "Vote has expired" with "Vote has ended"

Results page:
- [x] Results page only shows for closed votes
- [x] Results modifications from #242
(If grouping results not possible today, just do the rest of 242 and we'll finish that one part tomorrow)

Database changes:
- [x] Change "Which proposal are you most excited to learn more about?" question to "Which research would you like to see funded?"
- [x] Change "What is your favorit fruit?" to "What is your favourite fruit?"
- [x] Change "Berlin Research Society" to "Plural Research Experiment"

**Comment by lexicon-admin** [comment]
Since we need to test the results page changes, can we also add a new closed question?

Title: "What research would you most like to contribute to?"

Options / Descriptions: Same as for the currently open vote
