### ISSUE TITLE
List (and sort) authors by last name

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#285]
We've got a request to list and sort authors by last name (instead of username). I can see a couple of different problems, and a couple of different solutions:

### The "name" field is currently just one field

- We could make this two fields: "First Name" and "Last Name"
- We could assume that the text after the first space (if there is one) is the last name

### Not every user has a name

- We come make the name(s) fields compulsory
- We could sort by last name IF they provided a name, and username otherwise

I think the second option in each case is coolest if we can do it. But happy to take the "easy" way out in either case

The current user in the production database can be deleted if necessary to make this happen.

**Comment by diegoalzate** [comment]
i think the first solution is probably better

**Comment by MartinBenediktBusch** [comment]
The first solution (second option) would already be a problem with my name "Martin Benedikt Busch" which would result in "Benedikt Busch" as my last name. However, including a non-compulsory first name and last name field also does snot sound like a good option (unless we make it compulsory. 

What are the implications for comments and likes. I.e. use username for comments as we have it or also some combination of first name and last name?
