### ISSUE TITLE
Edit Berlin event text

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#290]
Update the Berlin event text in the database so it reads:

"The Plural Research society is tasked with distributing 100,000 ARB in grants using pluralistic methods.

Our first convening is May 28 at Factory Berlin Mitte. Participants will receive full details by email."

**Comment by MartinBenediktBusch** [comment]
Done: 

![Screenshot 2024-03-08 170710](https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/5499a77f-1ef9-4ad1-8749-b7d7c7cf8225)
