### ISSUE TITLE
Allow users to return to onboarding somehow

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#318]
It would be useful for users to be able to review the onboarding slides, but not important enough to add a nav bar link.

For now, the ideal place to achieve this would be via link from the holding page. Suggestions for how to achieve this welcome.

**Comment by camilovegag** [comment]
I'd go with a help icon, maybe we can expand the footer to look more like those at bigger pages, and we add this small icon at the right bottom corner:

![image](https://github.com/lexicongovernance/pluraltools-frontend/assets/59750365/fdf545bd-60cc-4528-96a6-f109bf804c55)

**Comment by MartinBenediktBusch** [comment]
I like the suggestion of Camillo, but maybe with more added text to make clear that this redirects to the onboarding page. Link on holding page is also good. However, the problem here is that people might want to look at the onboarding slides past registration (i.e. at the berlin event) when we are past the holding page.

**Comment by diegoalzate** [comment]
i like @camilovegag suggestion, I don't think going to onboarding slides past registration is an issue. It can be currently an issue as it goes to /account after. We could update this to go to the users homepage or we could create another page with the same info that has a `FAQ` structure with dropdowns. If i want to go back to the onboarding I might not be interested in reading everything just reading the question i want to answer.

**Comment by thewanderingeditor** [comment]
Sorry, just getting to this. I like @camilovegag's suggestion, but unfortunately the request has been upgraded to "make this part of the holding page text". i.e., Something like "Click here to review the community guidelines", with a link.

I suppose the two options then are:

- return to that slide somehow
- redirect to the text of the slide, duplicated somewhere else

**Comment by camilovegag** [comment]
Got it!

**Comment by camilovegag** [comment]
Closed as this was tackled on #325
