### ISSUE TITLE
New registration fields in staging

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#341]
Add two new optional questions related to research partners in event registration in staging:

1. Do you have a research partner, or advisor (if you are a junior researcher with less than PhD, JD, or equivalent)? - dropdown Yes / No
2. If Yes, what is their name?

**Comment by thewanderingeditor** [comment]
Should have specified this more clearly:

The text for the first question should just be "Do you have a research partner, or advisor (if you are a junior researcher with less than PhD, JD, or equivalent)?"

The answers should be "Yes" and "No" (currently they're "YES" and "NO")

There also seems to be a bug where not selecting an option prevents you from proceeding, even though the question is optional. Fine to make this required if easier.

**Comment by MartinBenediktBusch** [comment]
Implemented changes and made Yes no field required to solve the problem.
