### ISSUE TITLE
Update event description text and link

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#346]
Change the event description to:

"The Plural Research society is tasked with distributing 100,000 ARB in grants using pluralistic methods. Our first convening is May 28 from 10am to 5pm at Factory Berlin, Görlitzer Park, in the Lexis Room. Participants will receive full details by email."

Once 2.4 is live, the link should be https://maps.app.goo.gl/9HMd55XMhcvS994M8

**Comment by MartinBenediktBusch** [comment]
Text updated in staging and production. Insertion of link is blocked by https://github.com/lexicongovernance/pluraltools-backend/pull/266

**Comment by MartinBenediktBusch** [comment]
Inserted link in staging database @diegoalzate

**Comment by thewanderingeditor** [comment]
Updated requested text here is:

First Convening
May 28, 10am to 5pm
Factory Berlin, Gorlitzer Park, Lexis Room 
[Lohmühlenstraße 65, 12435, Berlin](https://maps.app.goo.gl/LwifAEB4FKM2hrUK8)

I interpret this as meaning First Convening should be the title, replacing Plural Research Experiment

I don't know if that box supports line breaks for the others. Also not sure if the event link can be made a hyperlink for the final line. If not, I think it's fine to have it as a fourth line.

**Comment by MartinBenediktBusch** [comment]
Following must be added to production once the new admin version is released that supports markdown: 

```
Updated requested text here is:

First Convening
May 28, 10am to 5pm
Factory Berlin, Gorlitzer Park, Lexis Room
[Lohmühlenstraße 65, 12435, Berlin](https://maps.app.goo.gl/LwifAEB4FKM2hrUK8)
```
