### ISSUE TITLE
Create separate page for Data Policy

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#367]
We will have a data policy on the site. This should live on a separate page (perhaps pluralresearch.org/data-policy) which can be linked from holding and agenda.

https://docs.google.com/document/d/1Xkynj5kAQvctvk8VtsP4odjJOuYI6APhr8uQoocWV90/edit

**Comment by camilovegag** [comment]
Created two Figma mockups for this:

[Privacy_Policy_720px.pdf](https://github.com/lexicongovernance/pluraltools-frontend/files/14872742/Privacy_Policy_720px.pdf)
[Privacy_Policy_1080px.pdf](https://github.com/lexicongovernance/pluraltools-frontend/files/14872743/Privacy_Policy_1080px.pdf)
