### ISSUE TITLE
Wrong display of hearts 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-frontend#439]
Somehow I encountered the case where the maximum number of available hearts is 14 instead of 20:

![HeartsBug](https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/c1462a7e-b5c2-47e1-9c5a-1e8b6374f284)

**Comment by MartinBenediktBusch** [comment]
@diegoalzate @camilovegag let me know if someone encounters the issue. Cannot reproduce. However, a logout solved the issue.

**Comment by diegoalzate** [comment]
did this happen on first login or after some interaction?

**Comment by MartinBenediktBusch** [comment]
@diegoalzate happens on first login.

**Comment by diegoalzate** [comment]
![CleanShot 2024-05-16 at 13 56 54](https://github.com/lexicongovernance/pluraltools-frontend/assets/22416585/460b4e5b-8f2e-4302-aadd-8b3ce7501588)
