### ISSUE TITLE
Adjust text on Polis group select page

### ISSUE THREAD

**Issue by thewanderingeditor** [lexicongovernance/pluraltools-frontend#464]
We have a request to alter the text on the Polis page

The alert title should just be POLIS

The text should be as minimal as possible:

![image](https://github.com/lexicongovernance/pluraltools-frontend/assets/29358947/cec6d9d9-145d-4761-827b-a0d9c4e743ec)

I think it's possible that this can't be achieved, because some of these parts can't be blank. A possible alternative is:

Title: Select your polis group
Text: [None]
Field title: Which group did the Polis visualization put you in?
Options: [Integers, determined on the day]

**Comment by MartinBenediktBusch** [comment]
Updated the test related to the database. The rest must be changed in the frontend.
