### ISSUE TITLE
Implement text changes 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-frontend#478]
Impelment the following text changes depicted in the screenshots: 

<img width="921" alt="Screen Shot 2024-05-09 at 8 21 03 PM" src="https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/7a306c80-0178-453e-85e6-0bd5642386ea">
<img width="872" alt="Screen Shot 2024-05-09 at 8 15 33 PM" src="https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/56eb2871-8301-404d-a65b-3cc26f90205f">
<img width="587" alt="Screen Shot 2024-05-09 at 8 15 20 PM" src="https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/1111a608-a9e0-448a-b1ac-e76e40e20bca">

**Comment by MartinBenediktBusch** [comment]
issue extends: https://github.com/lexicongovernance/pluraltools-frontend/issues/464

**Comment by thewanderingeditor** [comment]
I actually don't think this text is very useful. It was written before it was clear that groups wouldn't have leaders in a formal sense.

Better I think is:

Create a Research Group

Create a research group and share the access code with your collaborators. Assign proposals to groups from My Proposals.

In field -> Research group name

In box -> Access code for [name] research group


Join a Research Group

Ask the group creator for the access code

In field -> Enter access code


In general I would change "secret code" to "access code"
