### ISSUE TITLE
Make MY Proposals default page after approval 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-frontend#479]
MY PROPOSALS page should be the default once a propsal is approved and users are not re-directed to holding. The assumption is that Alearts related to secret groups are always active during the day.

![Screenshot 2024-05-15 201049](https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/6e074231-250f-4be4-95ac-f57787b84928)

**Comment by diegoalzate** [comment]
duplicate https://github.com/lexicongovernance/pluraltools-frontend/issues/471
