### ISSUE TITLE
Group registration bug

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-frontend#487]
When creating a registration for a group it redirects to the holding page because all my proposals that have been previously approved go back to a draft state.

**Comment by diegoalzate** [comment]
so i understand form this is that you have:
registrations: [approved, draft, draft]

and when you add another registration for a group it becomes this
registrations: [draft, draft, draft, draft]

is that the case? because we only redirect when the user has no approved registrations

**Comment by MartinBenediktBusch** [comment]
![Screenshot 2024-05-16 163053](https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/48d461fe-c44e-4482-b35d-c1d5575dc643)
![Screenshot 2024-05-16 163150](https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/c2328101-5fa0-423c-a2e1-b99660ad76d5)
![Screenshot 2024-05-16 163256](https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/123e1d53-a21a-4ffc-a1e2-f92ca39ec72b)
