### ISSUE TITLE
Kill header to give more space 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-frontend#495]
Kill the header plural research experiment and keep logo (and if you can't, the move ACCOUNT):

![kii](https://github.com/lexicongovernance/pluraltools-frontend/assets/43137759/0e38fedc-c518-42d2-905f-bafe90f8d2ae)

Maybe deleting sub-heading does the job.

**Comment by camilovegag** [comment]
Finally!
