### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by diegoalzate** [lexicongovernance/pluraltools-frontend#584]
## overview
Make the page mobile friendly so it can be demo on june 23 (10 working days). We are just missing the tables, as most of our page its mobile friendly by design.

**Comment by camilovegag** [comment]
Updating files here:
https://www.figma.com/proto/hvxad58SdqQ8PcZ44txe1u/Berlin?node-id=0-1&t=Web79PgnvgL6k7mV-1
