### ISSUE TITLE
Create Event Logo

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-frontend#620]
Create a custom Event Logo for Protocol Worlds at Edge Esmeralda. Maybe some inspiration can be found here: https://www.edgeesmeralda.com/ or https://summerofprotocols.com/

![Screenshot 2024-06-26 131006](https://github.com/lexicongovernance/edge-esmeralda/assets/43137759/36a037b8-8133-4a6a-962c-d0a6d5eb993f)

**Comment by camilovegag** [comment]
Closed by adding the island pine 8bit image
https://i.ibb.co/QMLCprk/edge-esmeralda.png
