### ISSUE TITLE
Handle `Save all votes` message 

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/pluraltools-frontend#80]
# Overview

Once you hit `Save all votes` on `events/:eventId/cycles/:cycleId`, the toast message should reflect the actual state. 
With the change introduced in [backend](https://github.com/lexicongovernance/forum-backend/pull/109), a proper error messaged should be displayed if the user tries to save votes on a `CLOSED` or `UPCOMING` cycle, we should also disable the button if that's the case.

<img width="700" alt="Screenshot 2024-01-29 at 10 21 17 AM" src="https://github.com/lexicongovernance/forum-frontend/assets/59750365/d00c1f8f-1907-46d0-be52-7bcd5359d203">

**Comment by MartinBenediktBusch** [comment]
Lets come back to this issue when the vote page is implemented in Berlin and see whether this is still relevant.
